---
version: 1.7.4
commit: Bump to version %.%.%
files:
  corekit/build.gradle: version = '%.%.%'
  uikit/build.gradle: version = '%.%.%'
  scancard/build.gradle: version = '%.%.%'
  widgets/build.gradle: version = '%.%.%'
